openapi: '3.0.2'
info:
  title: hitotsumami
  description: find recipe from some ingredients
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /post-recipe:
    post:
      tags: 
        - post
      description: post recipe
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/PostRecipe'
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error




components:
  schemas:
    PostRecipe: 
      type: object
      required:
        - user_id
        - name
        - seasonings
        - steps
      properties:
        user_id:
          type: string
        name:
          type: string
        description:
          type: string
        time_required_m: 
          type: integer
        seasonings:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name: 
                type: string
              quantity:
                type: string
        steps:
          type: array
          items:
            type: object
            required:
              - content
            properties:
              content:  
                type: string
        
