openapi: '3.0.2'
info:
  title: hitotsumami
  description: find recipe from some ingredients
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /recipes:
    post:
      security:
        - bearerAuth: []
      tags: 
        - recipe
      description: post recipe
      parameters:
        - in: header
          name: Authorization
          schema:
            $ref: '#/components/schemas/Authorization'
          required: true
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Recipe'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error
    
    get:  
      tags: 
        - recipe
      summary: get recipes 
      description: if you add query parameters, you can get recipes narrowed down by ingredient. and you can be sorted by good_ranking.
      parameters:
        - in: query
          name: ingredient_name
          schema: 
            type: array
            items: 
              type: string
        - in: query
          name: sort
          schema: 
            type: string
            enum: 
              - "good"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Recipe'
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error

  
  /recipes/{id}:
    get:
      summary: get the detail of one recipe
      tags: 
        - recipe
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error

  /users:
    post: 
      summary: user registration 
      tags: 
        - users
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: complete registration
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/User'
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error


  /login:
    post: 
      summary: user login
      tags: 
        - users
      requestBody:
        content:
          application/json:
            schema: 
              type: object
              required:
                - mail_address
                - password
              properties:
                mail_address:
                  type: string
                  example: 'aaa@example.com'
                password:
                  type: string
                  format: password
                  example: 'password'
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    description: bearer token
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
    delete:
      security:
        - bearerAuth: []
      tags:
        - users
      summary: user logout
      parameters:
        - in: header
          name: Authorization
          schema:
            $ref: '#/components/schemas/Authorization'
          required: true
      responses:
        '200':
          description: deleted
        '401':  
          description: Unauthorized
        '500':
          description: Internal Server Error
      



components:
  schemas:
    Authorization:
      description: "bearer token"
      example: "Bearer xxxxxxxxxxxxxxxxxxx"
    Recipe: 
      type: object
      required:
        - id
        - name
        - description
        - time_required_min
        - ingredients
        - seasonings
        - steps
      properties:
        id: 
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "おつまみキャベツ"
        ingredients:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name:
                type: string
                example: "キャベツ"
              quantity: 
                type: string
                example: "1/4"
        description:
          type: string
          example: "美味しいよ"
        time_required_min: 
          type: integer
          example: 10
        seasonings:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name: 
                type: string
                example: "ごま油"
              quantity:
                type: string
                example: "適量"
        steps:
          type: array
          items:
            type: object
            required:
              - content
            properties:
              content:  
                type: string
                example: "材料を切る"


    User:
      type: object
      required:
        - id
        - name
        - mail_address
        - password
      properties:
        id:
          type: integer
          readOnly: true
          example: 1
        name: 
          type: string
          example: 'user'
        mail_address:
          type: string
          example: 'aaa@example.com'
        password:
          type: string
          format: password
          writeOnly: true
          example: 'password'

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
  
        
