openapi: '3.0.2'
info:
  title: hitotsumami
  description: find recipe from some ingredients
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /post-recipe:
    post:
      tags: 
        - post
      description: post recipe
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/PostRecipe'
            example:
              user_id: 1
              name: "おつまみキャベツ"
              ingredients: [{"name": "キャベツ", "quantity":"1/4"}]
              description: "簡単にばくばく食べられます"
              time_required_min: 5
              seasonings: [{"name": "にんにく","quantity":"適量"},{"name": "塩","quantity":"適量"},{"name": "ごま油","quantity":"適量"}]
              steps: [{"content":"キャベツを切る"},{"content":"ジップロックに切ったキャベツと調味料を全部入れて混ぜる"}]

      responses:
        '200':
          description: OK
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error




components:
  schemas:
    PostRecipe: 
      type: object
      required:
        - user_id
        - name
        - ingredients
        - seasonings
        - steps
      properties:
        user_id:
          type: integer
        name:
          type: string
        ingredients:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name:
                type: string
              quantity: 
                type: number
                format: string
        description:
          type: string
        time_required_min: 
          type: integer
        seasonings:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name: 
                type: string
              quantity:
                type: string
        steps:
          type: array
          items:
            type: object
            required:
              - content
            properties:
              content:  
                type: string
        
