openapi: '3.0.2'
info:
  title: hitotsumami
  description: find recipe from some ingredients
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /recipes:
    post:
      security:
        - bearerAuth: []
      tags: 
        - recipe
      description: post recipe
      parameters:
        - in: header
          name: Authorization
          schema:
            $ref: '#/components/schemas/Authorization'
          required: true
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/PostRecipe'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostRecipe'
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error



components:
  schemas:
    Authorization:
      description: "bearer token"
      example: "Bearer xxxxxxxxxxxxxxxxxxx"
    PostRecipe: 
      type: object
      required:
        - name
        - description
        - time_required_min
        - ingredients
        - seasonings
        - steps
      properties:
        name:
          type: string
        ingredients:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name:
                type: string
              quantity: 
                type: string
        description:
          type: string
        time_required_min: 
          type: integer
        seasonings:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name: 
                type: string
              quantity:
                type: string
        steps:
          type: array
          items:
            type: object
            required:
              - content
            properties:
              content:  
                type: string
      example:
              name: "おつまみキャベツ"
              ingredients: [{"name": "キャベツ", "quantity":"1/4"}]
              description: "簡単にばくばく食べられます"
              time_required_min: 5
              seasonings: [{"name": "にんにく","quantity":"適量"},{"name": "塩","quantity":"適量"},{"name": "ごま油","quantity":"適量"}]
              steps: [{"content":"キャベツを切る"},{"content":"ジップロックに切ったキャベツと調味料を全部入れて混ぜる"}]

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
  
        
