openapi: '3.0.2'
info:
  title: hitotsumami
  description: find recipe from some ingredients
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /recipes:
    post:
      security:
        - bearerAuth: []
      tags: 
        - recipe
      description: post recipe
      parameters:
        - in: header
          name: Authorization
          schema:
            $ref: '#/components/schemas/Authorization'
          required: true
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Recipe'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '400':
          description: Bad Request 
        '500':
          description: Internal Server Error



components:
  schemas:
    Authorization:
      description: "bearer token"
      example: "Bearer xxxxxxxxxxxxxxxxxxx"
    Recipe: 
      type: object
      required:
        - id
        - name
        - description
        - time_required_min
        - ingredients
        - seasonings
        - steps
      properties:
        id: 
          type: integer
          readOnly: true
          example: 1
        name:
          type: string
          example: "おつまみキャベツ"
        ingredients:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name:
                type: string
                example: "キャベツ"
              quantity: 
                type: string
                example: "1/4"
        description:
          type: string
          example: "美味しいよ"
        time_required_min: 
          type: integer
          example: 10
        seasonings:
          type: array
          items:
            type: object
            required:
              - name
              - quantity
            properties:
              name: 
                type: string
                example: "ごま油"
              quantity:
                type: string
                example: "適量"
        steps:
          type: array
          items:
            type: object
            required:
              - content
            properties:
              content:  
                type: string
                example: "材料を切る"

  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT 
  
        
